### PR TITLE
Add gRPC-to-HTTP query fallback, fix test spicepod version, strengthen browser test assertions

### PR DESCRIPTION
**Pull request by lukekim**
## Summary

Four changes, from most to least significant:

### 1. SDK: fall back to HTTP when an Arrow Flight query fails mid-query

The Flight channel can initialize successfully but then fail on the query itself — observed as empty grpc-js status errors (`undefined undefined: undefined`) from the SDK running inside Vercel serverless functions, which made all Cloud Tests fail with 500s from the test app. Previously `doQueryRequest` only fell back to HTTP when channel *initialization* failed.

Now `sql()` falls back to HTTP on a failed Flight query, unless:
- `flightOnly` is set (no HTTP transport to fall back to), or
- partial results were already streamed to the caller's callback (fallback would deliver duplicate data).

`sqlJson()` in gRPC mode routes through `sql()` and inherits the same behavior. Falling back logs a warning through the configurable logger.

### 2. SDK: send raw SQL over HTTP unless parameters require the JSON envelope

Deploying fix 1 exposed a second bug: Spice Cloud's `/v1/sql` parses every request body as raw SQL and rejects the `{sql, parameters}` JSON envelope (introduced in #268) with `400 ParserError`. The OSS runtime accepts both formats (verified against the runtime source and a local spiced).

- Queries **without parameters** are sent as `text/plain` raw SQL — the format every endpoint accepts, and the pre-#268 behavior.
- **Parameterized** queries keep the JSON envelope against the OSS runtime.
- Parameterized queries **over HTTP against Spice Cloud** fail fast with a clear error (parameter binding there requires Arrow Flight) instead of a cryptic server 400.

New unit tests in `test/grpc-http-fallback.test.ts` cover all paths (6 tests), wired into the Local Runtime CI job.

### 3. CI: fix test spicepod version (`v1beta1` → `v1`)

CI installs the latest spiced release, which dropped support for `v1beta1` spicepods — the runtime failed to start and all six Local Runtime jobs failed with `ECONNREFUSED`. Validated against a local spiced before pushing.

### 4. Tests: strengthen browser client assertions for HTTP request formats

- Plain `sql()` asserts the `text/plain` raw-SQL body; a new test asserts the JSON envelope for parameterized queries.
- `sqlJson()` test asserts `Content-Type: text/plain` with the raw SQL body and the `application/vnd.spiceai.sql.v1+json` Accept header.
- The config-logging test now sets `SPICE_DEBUG=true` (restored after), making it deterministic regardless of `NODE_ENV`.

## Testing

- `test/grpc-http-fallback.test.ts` — 6 tests pass
- `npm run test:browser` — 62 tests pass
- Both body formats verified 200 OK against a local OSS spiced; the envelope-vs-raw behavior of Spice Cloud confirmed from CI logs (`ParserError` on `{`)
- Prettier clean; eslint delta on changed files is zero (repo-wide lint issues are pre-existing)

### CODE REVIEW

File: test/browser/client.test.ts [hunk 1]
```diff
@@ -38,9 +38,11 @@ describe('Browser SpiceClient', () => {
       expect(customClient).toBeInstanceOf(SpiceClient);
     });
 
-    test('should log configuration on initialization', () => {
+    test('should log configuration on initialization when SPICE_DEBUG is set', () => {
       consoleLogSpy.mockRestore();
       const debugSpy = jest.spyOn(console, 'debug').mockImplementation();
+      const originalEnv = process.env.SPICE_DEBUG;
+      process.env.SPICE_DEBUG = 'true';
```
[the remark this answers is not in the document]
Comment (lukekim) [reply test/browser/client.test.ts:46]: Fixed in 9df95f2 — the test now restores SPICE_DEBUG in a finally block, so a failing assertion can no longer leak it into later tests. The restore also deletes the variable when it was originally unset (assigning undefined to process.env would store the string "undefined").

File: src/client-common.ts [hunk 2]
```diff
@@ -773,15 +805,31 @@ export class SpiceClient {
...
+        parameters: httpParameters,
+      });
+      contentType = 'application/json';
+    }
 
     const requestHeaders: { [key: string]: string } = {
-      'Content-Type': 'application/json',
+      'Content-Type': contentType,
       Accept: acceptHeader,
     };
```
[the remark this answers is not in the document]
Comment (lukekim) [reply src/client-common.ts:839]: Fixed in 9df95f2 — custom headers now merge before the computed values, so the SDK-chosen Content-Type/Accept always win and can no longer be desynced from the conditionally-chosen body format. Unrelated custom headers still pass through; added a unit test locking in the precedence. (Instance-level customHeaders were already safe — they merge earlier in fetchInternal — this closes the per-call headers path.)

**Review by sgrebnov — APPROVED** [review]

**Review by ewgenius — APPROVED** [review]
